### PR TITLE
Fix some issues with recv hanging

### LINKED ISSUE #94: Nimbus livelock in recvMsg
https://gist.github.com/stefantalpalaru/311ea3e48f104250c6c3dbc4ee0b3718

### PR DESCRIPTION
**Pull request by Menduist**
Hopefully, closes #94

### CODE REVIEW

File: websock/session.nim [hunk 1]
```diff
@@ -347,8 +352,8 @@ proc recv*(
         trace "Reading bytes from frame stream", len
         let read = await ws.frame.read(ws.stream.reader, addr pbuffer[consumed], len)
         if read <= 0:
-          trace "Didn't read any bytes, breaking"
-          break
+          trace "Didn't read any bytes, stopping"
+          raise newException(WSClosedError, "WebSocket is closed!")
```
Comment (Menduist) [inline websock/session.nim:356]: read = 0 means EOF

File: websock/frame.nim [hunk 2]
```diff
@@ -205,6 +205,9 @@ proc decode*(
 
   frame.length = finalLen
 
+  if frame.length > WSMaxMessageSize:
```
Comment (Menduist) [inline websock/frame.nim:208]: A too big frame.length (of instance 13402712495349628929) causes issues in recv, capping it here

**Comment by dryajov** [comment]
Also, are you fuzing it to get this failures or doing something else?

File: websock/session.nim (hunk 1 above)
Comment (arnetheduck) [reply websock/session.nim:356]: the point with returning 0 on EOF is that exceptions are generally not suitable for entirely normal behavior - ie this way, a 100% correct application that closes the stream regularly cannot work without at least one exception being fired - I'd generally expect this of any `recv`-style function (recv itself in bsd sockets works this way - it returns 0 on EOF and -1 on errors)

Comment (arnetheduck) [reply websock/session.nim:356]: (to be clear, this `recv` function should also return 0 on a regular stream closure)

Comment (Menduist) [reply websock/session.nim:356]: Like often, the line between "regular behavior" and "exceptional behavior" gets fuzzy
Here for instance, this is not a regular behavior, because the client is closing the connection "unsafely", in the middle of the frame

More importantly, websocket allows empty frame, which would "legally" return 0 from `recvMsg`
So unfortunately, from this procedure, the only way I currently have to tell `recvMsg` that the stream is closed is through an exception

Comment (arnetheduck) [reply websock/session.nim:356]: > Here for instance, this is not a regular behavior, because the client is closing the connection "unsafely", in the middle of the frame

ah, fair point then - in general cases, it's not much of a "fuzzy" border for `recv` - it's more of a convention that's quite common (which `readOnce` generally continues, as a tradition), that closing is not considered an error at all (regardless of error reporting method) if it's done through a "regular" `close`

**Comment by Menduist** [comment]
Yes fuzzing only, I'll share my setup & tests soon

**Comment by Menduist** [comment]
Autobahn passed, merging
